Document: protos-sip
Title: Debian protos-sip Manual
Author: <insert document author here>
Abstract: This manual describes what protos-sip is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/protos-sip/protos-sip.sgml.gz

Format: postscript
Files: /usr/share/doc/protos-sip/protos-sip.ps.gz

Format: text
Files: /usr/share/doc/protos-sip/protos-sip.text.gz

Format: HTML
Index: /usr/share/doc/protos-sip/html/index.html
Files: /usr/share/doc/protos-sip/html/*.html
